# Generated by Django 4.2.5 on 2023-09-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.CharField(default='1', max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('TotalAmount', models.IntegerField(blank=True, null=True)),
                ('Cakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.cakes')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views.customer')),
            ],
        ),
    ]
